SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:postgres@localhost/tavish-krypto'
JWT_SIGNING_KEY = 'password'
JWT_SIGNING_ALGORITHM = 'HS256'
SENDGRID_API_KEY = 'SENDGRID_API_KEY'
SENDGRID_SENDER_EMAIL = 'x@y.z'
CELERY_BROKER = 'amqp://guest:guest@localhost:5672'
